const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const fs=require('fs');const path=require('path');
(async()=>{const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH,headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const token=fs.readFileSync(process.env.UI_TOKEN_FILE,'utf8').trim();await page.goto(process.env.UI_URL||'http://127.0.0.1:8024/');
await page.locator('#login').waitFor({state:'visible'});if(await page.locator('#app').isVisible())throw Error('App exposed before login');
const out=path.resolve('docs/screenshots');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'login.jpg'),quality:80});
await page.locator('#credential').fill('wrong-password');await page.locator('#connect').click();await page.locator('#loginError').filter({hasText:'不正确'}).waitFor();
await page.locator('#credential').fill(token);await page.locator('#connect').click();await page.locator('#app').waitFor({state:'visible'});
await page.locator('#task').fill('修复加法计算错误，查看差异并运行测试');await page.locator('#send').click();
await page.locator('#live').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#liveText').textContent.length>0);const firstDelta=await page.locator('#liveText').innerText();
await page.getByRole('button',{name:'批准并继续',exact:true}).waitFor({timeout:30000});
if(!(await page.locator('#approvals').innerText()).includes('return a + b'))throw Error('Missing diff');
await page.screenshot({path:path.join(out,'approval.jpg'),fullPage:true,quality:80});
await page.getByRole('button',{name:'批准并继续',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#approvals').textContent.includes('运行测试'));
await page.getByRole('button',{name:'批准并继续',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='已完成',{timeout:30000});
if(!(await page.locator('#stats').innerText()).includes('测试通过'))throw Error('Tests not passed');
await page.reload();await page.locator('#app').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#status').textContent==='已完成');
await page.screenshot({path:path.join(out,'desktop.jpg'),fullPage:true,quality:80});
await page.locator('#search').fill('不会匹配的标题');if(await page.locator('#sessions .session').count())throw Error('Search failed');await page.locator('#search').fill('');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile.jpg'),fullPage:true,quality:75});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow||errors.length)throw Error(JSON.stringify({overflow,errors}));
await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});
const report={mode:'offline_delayed_stream_fixture',checks:['login_screen','bad_password','cookie_login','live_text_before_completion','SSE_trace','edit_auto_resume','tests_auto_resume','reload_session_and_login','session_search','mobile_no_overflow','logout'],firstDelta,pageErrors:errors,passed:true};fs.writeFileSync('evaluation/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
